# [자스인 2주차] 윤진

[🐠 공부 정리 ](#-공부-정리)
[🧐 질문 ](#-질문)

# 🐠 공부 정리

# 10. 에러 헨들링

## 'try..catch' 문법

```js
try {
  // 코드...
} catch (err) {
  // 에러 핸들링
}
```

1. `try {...}` 안의 코드가 실행
2. 에러가 없다면, try 안의 마지막 줄까지 실행되고, catch 블록은 건너뜀
3. 에러가 있다면, try 안 코드의 실행이 중단되고, catch(err) 블록으로 제어 흐름이 넘어감. 변수 err(아무 이름이나 사용 가능)는 무슨 일이 일어났는지에 대한 설명이 담긴 에러 객체를 포함

try..catch는 오직 런타임 에러에만 동작. 코드가 문법적으로 잘못된 경우엔 try..catch가 동작하지 않음

setTimeout처럼 ‘스케줄 된’ 코드에서 발생한 예외는 try..catch에서 잡아낼 수 없음

```js
try {
  setTimeout(function () {
    noSuchVariable; // 스크립트는 여기서 죽습니다.
  }, 1000);
} catch (e) {
  alert("작동 멈춤");
}
```

setTimeout에 넘겨진 익명 함수는 엔진이 try..catch를 떠난 다음에서야 실행되기 때문임

```js
setTimeout(function () {
  try {
    noSuchVariable; // 이제 try..catch에서 에러를 핸들링 할 수 있습니다!
  } catch {
    alert("에러를 잡았습니다!");
  }
}, 1000);
```

## 에러 객체

에러가 발생하면 자바스크립트는 에러 내용이 담긴 객체를 생성

- name : 에러 이름. 정의되지 않은 변수 때문에 발생한 에러라면 "ReferenceError"가 이름
- message :에러 상세 내용을 담고 있는 문자 메시지
- stack : 현재 호출 스택. 에러를 유발한 중첩 호출들의 순서 정보를 가진 문자열로 디버깅 목적으로 사용

```js
try {
  lalala; // 에러, 변수가 정의되지 않음!
} catch (err) {
  alert(err.name); // ReferenceError
  alert(err.message); // lalala is not defined
  alert(err.stack); // ReferenceError: lalala is not defined at ... (호출 스택)

  // 에러 전체를 보여줄 수도 있습니다.
  // 이때, 에러 객체는 "name: message" 형태의 문자열로 변환됩니다.
  alert(err); // ReferenceError: lalala is not defined
}
```

## ‘throw’ 연산자

throw 연산자 : 에러를 생성

```js
throw <error object>
```

잘못된 데이터를 받았을 때

```js
try {
  JSON.parse("{ 잘못된 형식의 json o_O }");
} catch (e) {
  alert(e.name); // SyntaxError
  alert(e.message); // Unexpected token b in JSON at position 2
}
```

throw 연산자를 사용해 에러 던지기

```js
let json = '{ "age": 30 }'; // 불완전한 데이터

try {
  let user = JSON.parse(json); // <-- 에러 없음

  if (!user.name) {
    throw new SyntaxError("불완전한 데이터: 이름 없음"); // message를 이용해 SyntaxError를 생성
  }

  alert(user.name);
} catch (e) {
  alert("JSON Error: " + e.message); // JSON Error: 불완전한 데이터: 이름 없음
}
```

에러가 발생했으므로 try의 실행은 즉시 중단되고 제어 흐름이 catch로 넘어감

## 에러 다시 던지기

```js
let json = '{ "age": 30 }'; // 불완전한 데이터

try {
  user = JSON.parse(json); // <-- user 앞에 let을 붙이는 걸 잊었네요.

  // ...
} catch (err) {
  alert("JSON Error: " + err); // JSON Error: ReferenceError: user is not defined
  // (실제론 JSON Error가 아닙니다.)
}
```

**catch는 알고 있는 에러만 처리하고 나머지는 ‘다시 던져야’ 함**

1. catch가 모든 에러를 받기
2. catch(err) {...} 블록 안에서 에러 객체 err를 분석
3. 에러 처리 방법을 알지 못하면 throw err를 함

```js
// 보통 에러 타입을 instanceof 명령어로 체크
try {
  user = {
    /*...*/
  };
} catch (err) {
  if (err instanceof ReferenceError) {
    alert("ReferenceError"); //  정의되지 않은 변수에 접근하여 'ReferenceError' 발생
  }
}
```

try..catch를 하나 더 만들어, 다시 던져진 예상치 못한 에러를 처리

```js
function readData() {
  let json = '{ "age": 30 }';

  try {
    // ...
    blabla(); // 에러!
  } catch (e) {
    // ...
    if (!(e instanceof SyntaxError)) {
      throw e; // 알 수 없는 에러 다시 던지기
    }
  }
}

try {
  readData();
} catch (e) {
  alert("External catch got: " + e); // 에러를 잡음
}
```

## try…catch…finally

finally안의 코드가 실행되는 상황

- 에러가 없는 경우: try 실행이 끝난 후
- 에러가 있는 경우: catch 실행이 끝난 후

```js
try {
  alert("try 블록 시작");
  if (confirm("에러를 만드시겠습니까?")) 이상한_코드();
} catch (e) {
  alert("catch");
} finally {
  alert("finally");
}
```

1. "에러를 만드시겠습니까?"에 'OK’로 답한 경우: try -> catch -> finally
2. 'No’로 답한 경우: try -> finally

finally 절은 무언가를 실행하고, 실행 결과에 상관없이 실행을 완료하고 싶을 경우 사용

## finally 와 return

finally 절은 try..catch 절을 빠져나가는 어떤 경우에도 실행  
return을 사용해 명시적으로 빠져나가려는 경우도 마찬가지

```js
function func() {
  try {
    return 1;
  } catch (e) {
    /* ... */
  } finally {
    alert("finally");
  }
}

alert(func()); // finally 안의 alert가 실행되고 난 후, 실행됨
```

try 블록 안에 return이 있지만 값이 바깥 코드로 반환되기 전에 finally가 실행

try..catch가 없어도 대부분의 호스트 환경이 ‘전역’ 에러 핸들러를 지원하기 때문에 ‘떨어져 나온’ 에러를 잡을 수 있음  
window.onerror는 브라우저 환경의 전역 에러 핸들러

## 에러 확장하기

```js
// 문제가 되는 필드 정보가 저장
class ValidationError extends Error {
  constructor(message) {
    super(message); // 부모 생성자에서 설정된 message 프로퍼티 호출
    this.name = "ValidationError"; // name 프로퍼티도 에러로 설정해야 하기 때문에 원하는 값으로 재설정
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new ValidationError("No field: age");
  }
  if (!user.name) {
    throw new ValidationError("No field: name");
  }

  return user;
}

// try..catch와 readUser를 함께 사용한 예시

try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No field: name
  } else if (err instanceof SyntaxError) {
    // instanceof로 에러 유형을 확인
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기 합니다.
  }
}
```

```js
// ...
// (err instanceof SyntaxError) 대신 사용 가능하지만 잘 사용하지 않음
} else if (err.name == "SyntaxError") { // (*)
// ...
```

## 예외 감싸기

```js
try {
  ...
  readUser()  // 잠재적 에러 발생처
  ...
} catch (err) {
  if (err instanceof ValidationError) {
    // validation 에러 처리
  } else if (err instanceof SyntaxError) {
    // 문법 에러 처리
  } else {
    throw err; // 알 수 없는 에러는 다시 던지기 함
  }
}
```

현재 에러 처리 스키마엔 두 종류의 에러만 나와 있음. 그런데 에러의 종류는 더 추가될 수 있음

에러 종류가 많아질 텐데 그때마다 에러 종류에 따라 에러 처리 분기문을 매번 추가해야 하나?

그렇지 않음.  
실제 우리가 필요로 하는 정보는 ‘데이터를 읽을 때’ 에러가 발생했는지에 대한 여부

예외 감싸기 : 종류별 에러를 좀 더 추상적인 에러, ReadError에 하나로 모아(wrap) 처리

1. '데이터 읽기’와 같은 포괄적인 에러를 대변하는 새로운 클래스 ReadError를 만듦
2. 함수 readUser 발생한 ValidationError, SyntaxError 등의 에러는 readUser 내부에서 잡고 이때 ReadError를 생성
3. ReadError 객체의 cause 프로퍼티엔 실제 에러에 대한 참조가 저장

```js
class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = "ReadError";
  }
}

class ValidationError extends Error {
  /*...*/
}
class PropertyRequiredError extends ValidationError {
  /* ... */
}

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError("age");
  }

  if (!user.name) {
    throw new PropertyRequiredError("name");
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError("Syntax Error", err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError("Validation Error", err);
    } else {
      throw err;
    }
  }
}

try {
  readUser("{잘못된 형식의 json}");
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert("Original error: " + e.cause);
  } else {
    throw e;
  }
}
```

# 11. 프라미스와 async, await

## 콜백

함수 `loadScript(src)`는 `<script src="…">`를 동적으로 만들고 이를 문서에 추가  
브라우저는 자동으로 태그에 있는 스크립트를 불러오고, 로딩이 완료되면 스크립트를 실행

```js
function loadScript(src) {
  // <script> 태그를 만들고 페이지에 태그를 추가합니다.
  // 태그가 페이지에 추가되면 src에 있는 스크립트를 로딩하고 실행합니다.
  let script = document.createElement("script");
  script.src = src;
  document.head.append(script);
}
```

이 스크립트는 ‘비동기적으로’ 실행  
로딩은 지금 당장 시작되더라도 실행은 함수가 끝난 후에야 되기 때문  
`loadScript(…)` 아래에 있는 코드들은 스크립트 로딩이 종료되는 걸 기다리지 않음

```js
// 해당 경로에 위치한 스크립트를 불러오고 실행함
loadScript("/my/script.js");
// loadScript 아래의 코드는
// 스크립트 로딩이 끝날 때까지 기다리지 않습니다.
// ...
```

그런데 loadScript(...)를 호출하자마자 내부 함수를 호출하면 원하는 대로 작동하지 않음

```js
loadScript("/my/script.js"); // script.js엔 "function newFunction() {…}"이 있습니다.

newFunction(); // 함수가 존재하지 않는다는 에러가 발생합니다!
```

에러는 브라우저가 스크립트를 읽어올 수 있는 시간을 충분히 확보하지 못했기 때문에 발생  
지금은 함수 `loadScript`에서 스크립트 로딩이 완료되었는지 알 방법이 없음  
원하는 대로 스크립트 안의 함수나 변수를 사용하려면 스크립트 로딩이 끝났는지 여부를 알 수 있어야 함

loadScript의 두 번째 인수로 스크립트 로딩이 끝난 후 실행될 함수인 콜백(callback) 함수 추가

```js
function loadScript(src, callback) {
  let script = document.createElement("script");
  script.src = src;

  script.onload = () => callback(script);

  document.head.append(script);
}
```

새롭게 불러온 스크립트에 있는 함수를 콜백 함수 안에서 호출하면 원하는 대로 외부 스크립트 안의 함수를 사용할 수 있음

```js
loadScript('/my/script.js', function() {
  // 콜백 함수는 스크립트 로드가 끝나면 실행됩니다.
  newFunction(); // 이제 함수 호출이 제대로 동작합니다.
  ...
});
```

이렇게 두 번째 인수로 전달된 함수는 원하는 동작(위 예제에선 외부 스크립트를 불러오는 것)이 완료되었을 때 실행

실제 코드로 살펴보기

```js
function loadScript(src, callback) {
  let script = document.createElement("script");
  script.src = src;
  script.onload = () => callback(script);
  document.head.append(script);
}

loadScript(
  "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.js",
  (script) => {
    alert(`${script.src}가 로드되었습니다.`);
    alert(_); // 스크립트에 정의된 함수
  }
);
```

이런 방식이 ‘콜백 기반(callback-based)’ 비동기 프로그래밍  
무언가를 비동기적으로 수행하는 함수는 함수 내 동작이 모두 처리된 후 실행되어야 하는 함수가 들어갈 콜백을 인수로 반드시 제공해야 함

## 콜백 속 콜백

```js
loadScript("/my/script.js", function (script) {
  alert(`${script.src}을 로딩했습니다. 이젠, 다음 스크립트를 로딩합시다.`);

  loadScript("/my/script2.js", function (script) {
    alert(`두 번째 스크립트를 성공적으로 로딩했습니다.`);
  });
});
```

이렇게 콜백 안에 콜백을 넣는 것은 수행하려는 동작이 단 몇 개뿐이라면 괜찮지만, 동작이 많은 경우엔 좋지 않음

## 에러 핸들링

```js
function loadScript(src, callback) {
  let script = document.createElement("script");
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () =>
    callback(new Error(`${src}를 불러오는 도중에 에러가 발생했습니다.`));

  document.head.append(script);
}
```

```js
loadScript("/my/script.js", function (error, script) {
  if (error) {
    // 에러 처리
  } else {
    // 스크립트 로딩이 성공적으로 끝남
  }
});
```

이런 패턴이 '오류 우선 콜백(error-first callback);

1. callback의 첫 번째 인수는 에러를 위해 남겨둠. 에러가 발생하면 이 인수를 이용해 callback(err)이 호출
2. 두 번째 인수(필요하면 인수를 더 추가할 수 있음)는 에러가 발생하지 않았을 때를 위해 남겨둠. 원하는 동작이 성공한 경우엔 callback(null, result1, result2...)이 호출

## 프라미스

이해를 위해 상황을 가정해 보자

나는 가수  
다음 앨범이 언제 나오는지 궁금한 팬들에게 자동으로 소식을 받아볼 수 있도록 하기 위해 구독 리스트를 만들어 전달  
앨범이 준비되면 리스트에 있는 팬들에게 소식 알림

1. '제작 코드(producing code)'는 원격에서 스크립트를 불러오는 것 같은 시간이 걸리는 일을 함. 위 비유에선 '가수’가 제작 코드에 해당
2. '소비 코드(consuming code)'는 '제작 코드’의 결과를 기다렸다가 이를 소비함. 이때 소비 주체(함수)는 여럿이 될 수 있고, 위 비유에서 소비 코드는 '팬’
3. 프라미스(promise) 는 '제작 코드’와 '소비 코드’를 연결해 주는 특별한 자바스크립트 객체. 위 비유에서 프라미스는 '구독 리스트’. '프라미스’는 시간이 얼마나 걸리든 상관없이 약속한 결과를 만들어 내는 '제작 코드’가 준비되었을 때, 모든 소비 코드가 결과를 사용할 수 있도록 해줌

```js
let promise = new Promise(function (resolve, reject) {
  // executor (제작 코드, '가수')
});
```

`new Promise`에 전달되는 함수는 executor(실행자, 실행 함수) 라고 부름  
executor는 new Promise가 만들어질 때 자동으로 실행되는데, 결과를 최종적으로 만들어내는 제작 코드를 포함함

executor의 인수 `resolve`와 `reject`는 자바스크립트에서 자체 제공하는 콜백, 상황에 따라 인수로 넘겨준 콜백 중 하나를 반드시 호출

- `resolve(value)` — 일이 성공적으로 끝난 경우 그 결과를 나타내는 value와 함께 호출
- `reject(error)` — 에러 발생 시 에러 객체를 나타내는 error와 함께 호출

executor는 자동으로 실행되고, 여기서 원하는 일이 처리  
처리가 끝나면 executor는 처리 성공 여부에 따라 `resolve`나 `reject`를 호출

new Promise 생성자가 반환하는 promise 객체가 가지는 내부 프로퍼티

- `state` : 처음엔 "pending"(보류)이었다 resolve가 호출되면 "fulfilled", reject가 호출되면 "rejected"로 변함
- `result` : 처음엔 undefined이었다 resolve(value)가 호출되면 value로, reject(error)가 호출되면 error로 변함

![image](https://github.com/user-attachments/assets/17bbdbfa-1b0a-4bae-bef6-5acf510f1430)

```js
let promise = new Promise(function (resolve, reject) {
  // 프라미스가 만들어지면 executor 함수는 자동으로 실행됩니다.

  // 1초 뒤에 일이 성공적으로 끝났다는 신호가 전달되면서 result는 '완료'가 됩니다.
  setTimeout(() => resolve("완료"), 1000);
});
```

![image](https://github.com/user-attachments/assets/faedd5d2-6e2a-4591-9735-df2755f87483)

일이 성공적으로 처리되었을 때의 프라미스는 'fulfilled promise(약속이 이행된 프라미스)'

```js
let promise = new Promise(function (resolve, reject) {
  // 1초 뒤에 에러와 함께 실행이 종료되었다는 신호를 보냅니다.
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});
```

![image](https://github.com/user-attachments/assets/fd4503e9-82c9-447d-90d9-7821d14e1349)

요약 : executor는 보통 시간이 걸리는 일을 수행하고, 일이 끝나면 resolve나 reject 함수를 호출하는데, 이때 프라미스 객체의 상태가 변화

이행(resolved) 혹은 거부(rejected) 상태의 프라미스는 ‘처리된(settled)’ 프라미스  
반대되는 프라미스로 '대기(pending)'상태의 프라미스

### resolve·reject 함수 즉시 호출하기

executor는 대개 무언가를 비동기적으로 수행하고, 약간의 시간이 지난 후에 `resolve`, `reject`를 호출하는데, 즉시 호출할 수도 있음

```js
let promise = new Promise(function (resolve, reject) {
  // 일을 끝마치는 데 시간이 들지 않음
  resolve(123); // 결과(123)를 즉시 resolve에 전달함
});
```

## 소비자: then, catch, finally

프라미스 객체는 executor(‘제작 코드’ 혹은 ‘가수’)와 결과나 에러를 받을 소비 함수(‘팬’)를 이어주는 역할  
소비함수는 .then, .catch, .finally 메서드를 사용해 등록(구독)

## then

```js
promise.then(
  function (result) {
    /* 결과(result)를 다룹니다 */
  },
  function (error) {
    /* 에러(error)를 다룹니다 */
  }
);
```

성공적으로 이행된 프라미스

```js
let promise = new Promise(function (resolve, reject) {
  setTimeout(() => resolve("완료!"), 1000);
});

// resolve 함수는 .then의 첫 번째 함수(인수)를 실행합니다.
promise.then(
  (result) => alert(result), // 1초 후 "완료!"를 출력
  (error) => alert(error) // 실행되지 않음
);
```

프라미스가 거부된 경우

```js
let promise = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// reject 함수는 .then의 두 번째 함수를 실행합니다.
promise.then(
  (result) => alert(result), // 실행되지 않음
  (error) => alert(error) // 1초 후 "Error: 에러 발생!"을 출력
);
```

성공 처리만 다루고 싶다면 인수 하나만 전달

```js
let promise = new Promise((resolve) => {
  setTimeout(() => resolve("완료!"), 1000);
});

promise.then(alert); // 1초 뒤 "완료!" 출력
```

## catch

에러가 발생한 경우만 다루고 싶다면 `.then(null, errorHandlingFunction)`같이 null을 첫 번째 인수로 전달하면 됨.  
`.catch(errorHandlingFunction)`를 써도 되는데, `.catch`는 `.then`에 null을 전달하는 것과 동일하게 작동

```js
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// .catch(f)는 promise.then(null, f)과 동일하게 작동합니다
promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
```

## finally

쓸모가 없어진 로딩 인디케이터(loading indicator)를 멈추는 경우같이, 결과가 어떻든 마무리가 필요하면 finally가 유용

```js
new Promise((resolve, reject) => {
  /* 시간이 걸리는 어떤 일을 수행하고, 그 후 resolve, reject를 호출함 */
})
  // 성공·실패 여부와 상관없이 프라미스가 처리되면 실행됨
  .finally(() => 로딩 인디케이터 중지)
  .then(result => result와 err 보여줌 => error 보여줌)
```

`finally`와 `.then(f, f)`의 차이점

1. `finally` 핸들러엔 인수가 없음. `finally`에선 프라미스가 이행되었는지, 거부되었는지 알 수 없음. `finally`에선 절차를 마무리하는 ‘보편적’ 동작을 수행하기 때문에 성공·실패 여부를 몰라도 됨
2. `finally` 핸들러는 자동으로 다음 핸들러에 결과와 에러를 전달

```js
new Promise((resolve, reject) => {
  setTimeout(() => resolve("결과"), 2000);
})
  .finally(() => alert("프라미스가 준비되었습니다."))
  .then((result) => alert(result)); // <-- .then에서 result를 다룰 수 있음
```

```js
new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
})
  .finally(() => alert("프라미스가 준비되었습니다."))
  .catch((err) => alert(err)); // <-- .catch에서 에러 객체를 다룰 수 있음
```

3. `.finally(f)`는 함수 `f`를 중복해서 쓸 필요가 없기 때문에 `.then(f, f)`보다 문법 측면에서 더 편리

프라미스가 대기 상태일 때, `.then/catch/finally` 핸들러는 프라미스가 처리되길 기다림  
반면, 프라미스가 이미 처리상태라면 핸들러가 즉각 실행됨

```js
// 아래 프라미스는 생성과 동시에 이행됩니다.
let promise = new Promise((resolve) => resolve("완료!"));

promise.then(alert); // 완료! (바로 출력됨)
```

## 프라미스 체이닝

```js
new Promise(function (resolve, reject) {
  setTimeout(() => resolve(1), 1000); // (*)
})
  .then(function (result) {
    // (**)

    alert(result); // 1
    return result * 2;
  })
  .then(function (result) {
    // (***)

    alert(result); // 2
    return result * 2;
  })
  .then(function (result) {
    alert(result); // 4
    return result * 2;
  });
```

![image](https://github.com/user-attachments/assets/064ac199-ff1d-4a7b-86f4-d9fdda50f2e3)

프라미스 체이닝이 가능한 이유는 `promise.then`을 호출하면 프라미스가 반환되기 때문  
반환된 프라미스엔 당연히 `.then`을 호출할 수 있음

핸들러가 값을 반환할 때엔 이 값이 프라미스의 result가 됨. 따라서 다음 `.then`은 이 값을 이용해 호출

프라미스 하나에 `.then`을 여러 개 추가한 후, 이를 체이닝이라고 착각하는 경우

```js
let promise = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(1), 1000);
});

promise.then(function (result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function (result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function (result) {
  alert(result); // 1
  return result * 2;
});
```

프라미스는 하나인데 등록된 핸들러는 여러 개, 하지만 이 핸들러들은 result를 순차적으로 전달하지 않고 독립적으로 처리하기에 프라미스 체이닝이 아님

![image](https://github.com/user-attachments/assets/c350118b-ed3f-43f5-958c-7102c085683a)

## 프라미스 반환하기

`.then(handler)`에 사용된 핸들러가 프라미스를 생성하거나 반환하는 경우  
이 경우 이어지는 핸들러는 프라미스가 처리될 때까지 기다리다가 처리가 완료되면 그 결과를 받음

```js
new Promise(function (resolve, reject) {
  setTimeout(() => resolve(1), 1000);
})
  .then(function (result) {
    alert(result); // 1

    return new Promise((resolve, reject) => {
      // 첫 번째 .then은 1을 출력하고 new Promise(…)를 반환
      setTimeout(() => resolve(result * 2), 1000);
    });
  })
  .then(function (result) {
    // 2를 출력하고 동일한 과정이 반복

    alert(result); // 2

    return new Promise((resolve, reject) => {
      setTimeout(() => resolve(result * 2), 1000);
    });
  })
  .then(function (result) {
    alert(result); // 4
  });
```

얼럿 창엔 이전 예시와 동일하게 1, 2, 4가 차례대로 출력되지만 얼럿 창 사이에 1초의 딜레이가 생김

## thenable

핸들러는 프라미스가 아닌 thenable이라 불리는 객체를 반환하기도 함  
then이라는 메서드를 가진 객체는 모두 thenable객체라고 부르는데, 이 객체는 프라미스와 같은 방식으로 처리

‘thenable’ 객체에 대한 아이디어는 서드파티 라이브러리가 ‘프라미스와 호환 가능한’ 자체 객체를 구현할 수 있다는 점에서 나옴. 이 객체들엔 자체 확장 메서드가 구현되어 있겠지만 `.then`이 있기 때문에 네이티브 프라미스와도 호환 가능

```js
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve); // function() { 네이티브 코드 }
    // 1초 후 this.num*2와 함께 이행됨
    setTimeout(() => resolve(this.num * 2), 1000); // (**)
  }
}

new Promise((resolve) => resolve(1))
  .then((result) => {
    return new Thenable(result); // (*)
  })
  .then(alert); // 1000밀리 초 후 2를 보여줌
```

- (\*)로 표시한 줄에서 .then 핸들러가 반환한 객체를 확인
- 이 객체에 호출 가능한 메서드 then이 있으면 then이 호출
- then은 resolve와 reject라는 네이티브 함수를 인수로 받고(executor과 유사함), 둘 중 하나가 호출될 때까지 기다림
  - 위 예시에서 resolve(2)는 1초 후에 호출((\*\*))
- 호출 후 결과는 체인을 따라 아래로 전달

## 프라미스와 에러 핸들링

프라미스가 거부되면 제어 흐름이 제일 가까운 `rejection` 핸들러로 넘어가기 때문에 프라미스 체인을 사용하면 에러를 쉽게 처리할 수 있음

```js
fetch("https://no-such-server.blabla") // 거부
  .then((response) => response.json())
  .catch((err) => alert(err)); // TypeError: failed to fetch (출력되는 내용은 다를 수 있음)
```

## 암시적 try…catch

프라미스 executor와 프라미스 핸들러 코드 주위엔 '보이지 않는(암시적) try..catch'가 있음  
예외가 발생하면 암시적 try..catch에서 예외를 잡고 이를 reject처럼 다룸

```js
new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
}).catch(alert); // Error: 에러 발생!

// 같은 동작
new Promise((resolve, reject) => {
  reject(new Error("에러 발생!"));
}).catch(alert); // Error: 에러 발생!
```

`.then` 핸들러 안에서 throw를 사용해 에러를 던지면, 이 자체가 거부된 프라미스를 의미

```js
new Promise((resolve, reject) => {
  resolve("OK");
})
  .then((result) => {
    throw new Error("에러 발생!"); // 프라미스가 거부됨
  })
  .catch(alert); // Error: 에러 발생!
```

## 다시 던지기

`.then` 핸들러를 원하는 만큼 사용하다 마지막에 `.catch `하나만 붙이면 `.then` 핸들러에서 발생한 모든 에러를 처리할 수 있음

```js
// 실행 순서: catch -> then
new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
})
  .catch(function (error) {
    alert("에러가 잘 처리되었습니다. 정상적으로 실행이 이어집니다.");
  })
  .then(() => alert("다음 핸들러가 실행됩니다."));
```

다시 던지기

```js
// 실행 순서: catch -> catch
new Promise((resolve, reject) => {
  throw new Error("에러 발생!");
})
  .catch(function (error) {
    // (*)

    if (error instanceof URIError) {
      // 에러 처리
    } else {
      alert("처리할 수 없는 에러");

      throw error; // 에러 다시 던지기
    }
  })
  .then(function () {
    /* 여기는 실행되지 않습니다. */
  })
  .catch((error) => {
    // (**)

    alert(`알 수 없는 에러가 발생함: ${error}`);
    // 반환값이 없음 => 실행이 계속됨
  });
```

실행 흐름이 첫 번째 `.catch (\*)`로 넘어갔다가 다음 `.catch (\*\*)`로 이어짐

## 처리되지 못한 거부

```js
new Promise(function () {
  noSuchFunction(); // 존재하지 않는 함수를 호출하기 때문에 에러가 발생함
}).then(() => {
  // 성공상태의 프라미스를 처리하는 핸들러. 한 개 혹은 여러 개가 있을 수 있음
}); // 끝에 .catch가 없음!
```

에러가 발생하면 프라미스는 거부상태가 되고, 실행 흐름은 가장 가까운 `rejection` 핸들러로 넘어감  
그런데 위 예시엔 예외를 처리해 줄 핸들러가 없어서 에러가 ‘갇혀버림’

브라우저 환경에선 이런 에러를 `unhandledrejection` 이벤트로 처리할 수 있음

```js
window.addEventListener("unhandledrejection", function (event) {
  // unhandledrejection 이벤트엔 두 개의 특수 프로퍼티가 있습니다.
  alert(event.promise); // [object Promise] - 에러를 생성하는 프라미스
  alert(event.reason); // Error: 에러 발생! - 처리하지 못한 에러 객체
});

new Promise(function () {
  throw new Error("에러 발생!");
}); // 에러를 처리할 수 있는 .catch 핸들러가 없음
```

## 프라미스 API

### Promise.all

Promise.all : 여러 개의 프라미스를 동시에 실행시키고 모든 프라미스가 준비될 때까지 기다릴 때 사용(복수의 URL에 동시에 요청을 보내고, 다운로드가 모두 완료된 후에 콘텐츠를 처리할 때)

```js
let promise = Promise.all([...promises...]);
```

Promise.all은 요소 전체가 프라미스인 배열(엄밀히 따지면 이터러블 객체이지만, 대개는 배열임)을 받고 새로운 프라미스를 반환

```js
Promise.all([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // 2
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)), // 3
]).then(alert); // 프라미스 전체가 처리되면 1, 2, 3이 반환됩니다. 각 프라미스는 배열을 구성하는 요소가 됩니다. [1, 2, 3]
```

Promise.all의 첫 번째 프라미스는 가장 늦게 이행되더라도 처리 결과는 배열의 첫 번째 요소에 저장

**Promise.all에 전달되는 프라미스 중 하나라도 거부되면, Promise.all이 반환하는 프라미스는 에러와 함께 바로 거부**

```js
Promise.all([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) =>
    setTimeout(() => reject(new Error("에러 발생!")), 2000)
  ),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),
]).catch(alert); // Error: 에러 발생!
```

이터러블 객체가 아닌 일반 값도 Promise.all(iterable)에 넘길 수 있음

```js
Promise.all([
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
  }),
  2,
  3,
]).then(alert); // 1, 2, 3
```

요소 ‘그대로’ 결과 배열에 전달

### Promise.allSettled

Promise.allSettled : 모든 프라미스가 처리될 때까지 기다림

반환되는 배열

- 응답이 성공할 경우 : {status:"fulfilled", value:result}
- 에러가 발생한 경우 : {status:"rejected", reason:error}

```js
let urls = [
  "https://api.github.com/users/iliakan",
  "https://api.github.com/users/Violet-Bora-Lee",
  "https://no-such-url",
];

Promise.allSettled(urls.map((url) => fetch(url))).then((results) => {
  // (*)
  results.forEach((result, num) => {
    if (result.status == "fulfilled") {
      alert(`${urls[num]}: ${result.value.status}`);
    }
    if (result.status == "rejected") {
      alert(`${urls[num]}: ${result.reason}`);
    }
  });
});
```

(\*)로 표시한 줄의 results

```js
[
  {status: 'fulfilled', value: ...응답...},
  {status: 'fulfilled', value: ...응답...},
  {status: 'rejected', reason: ...에러 객체...}
]
```

Promise.allSettled를 사용하면 이처럼 각 프라미스의 상태와 값 또는 에러를 받을 수 있음

### Promise.race

Promise.race : Promise.all과 비슷하지만 가장 먼저 처리되는 프라미스의 결과(혹은 에러)를 반환

```js
let promise = Promise.race(iterable);
```

```js
Promise.race([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) =>
    setTimeout(() => reject(new Error("에러 발생!")), 2000)
  ),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000)),
]).then(alert); // 1
```

첫 번째 프라미스가 가장 빨리 처리상태가 되기 때문에 첫 번째 프라미스의 결과가 result 값  
이렇게 Promise.race를 사용하면 '경주(race)의 승자’가 나타난 순간 다른 프라미스의 결과 또는 에러는 무시

## 프라미스화

프라미스화 : 콜백을 받는 함수를 프라미스를 반환하는 함수로 바꾸는 것

콜백

```js
function loadScript(src, callback) {
  let script = document.createElement("script");
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () =>
    callback(new Error(`${src}를 불러오는 도중에 에러가 발생함`));

  document.head.append(script);
}

// 사용법:
// loadScript('path/script.js', (err, script) => {...})
```

loadScript(src, callback)를 프라미스화  
새로운 함수 loadScriptPromise(src)는 loadScript와 동일하게 동작하지만 callback을 제외한 src만 인수로 받아야 하고, 프라미스를 반환해야 함

```js
let loadScriptPromise = function (src) {
  return new Promise((resolve, reject) => {
    loadScript(src, (err, script) => {
      if (err) reject(err);
      else resolve(script);
    });
  });
};

// 사용법:
// loadScriptPromise('path/script.js').then(...)
```

## 마이크로태스크 큐

마이크로태스크 뮤 : 비동기 작업을 처리하기 위한 관리

- 마이크로태스크 큐는 먼저 들어온 작업을 먼저 실행(FIFO, first-in-first-out)
- 실행할 것이 아무것도 남아있지 않을 때만 마이크로태스크 큐에 있는 작업이 실행

어떠한 프라미스가 준비되었을 때 이 프라미스의 `.then/catch/finally` 핸들러가 큐에 들어가는 것  
이때 핸들러들은 여전히 실행되지 않고 현재 코드에서 자유로운 상태가 되었을 때에서야 자바스크립트 엔진은 큐에서 작업을 꺼내 실행함

```js
let promise = Promise.resolve();

promise.then(() => alert("프라미스 성공!"));

alert("코드 종료"); // 얼럿 창이 가장 먼저 뜹니다.
```

![image](https://github.com/user-attachments/assets/ef36cb53-73e1-4b7d-9057-1c8010d09832)

프라미스 핸들러는 항상 내부 큐를 통과

여러 개의 `.then/catch/finally`를 사용해 만든 체인의 경우, 각 핸들러는 비동기적으로 실행  
큐에 들어간 핸들러 각각은 현재 코드가 완료되고, 큐에 적체된 이전 핸들러의 실행이 완료되었을 때 실행

실행 순서가 중요한 경우엔 이런 요구사항이 충족되도록 코드를 작성

```js
Promise.resolve()
  .then(() => alert("프라미스 성공!"))
  .then(() => alert("코드 종료"));
```

## 처리되지 못한 거부

**’처리되지 못한 거부’는 마이크로태스크 큐 끝에서 프라미스 에러가 처리되지 못할 때 발생**

`.catch`를 추가해주는 걸 잊은 경우, 엔진은 마이크로태스크 큐가 빈 이후에 `unhandledrejection` 이벤트를 트리거

```js
let promise = Promise.reject(new Error("프라미스 실패!"));

// 프라미스 실패!
window.addEventListener("unhandledrejection", (event) => alert(event.reason));
```

setTimeout을 이용해 에러를 나중에 처리하면 어떻게 될까?

```js
let promise = Promise.reject(new Error("프라미스 실패!"));
setTimeout(() => promise.catch((err) => alert("잡았다!")), 1000);

// Error: 프라미스 실패!
window.addEventListener("unhandledrejection", (event) => alert(event.reason));
```

`unhandledrejection`은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성  
엔진은 프라미스들을 검사하고 이 중 하나라도 ‘거부(rejected)’ 상태이면 `unhandledrejection` 핸들러를 트리거  
`.catch`는 `unhandledrejection`이 발생한 이후에 트리거

## async 함수

```js
async function f() {
  return 1;
}
```

function 앞에 async를 붙이면 해당 함수는 항상 프라미스를 반환  
프라미스가 아닌 값을 반환하더라도 이행 상태의 프라미스(resolved promise)로 값을 감싸 이행된 프라미스가 반환되도록 함

## await

```js
// await는 async 함수 안에서만 동작합니다.
let value = await promise;
```

자바스크립트는 await 키워드를 만나면 프라미스가 처리될 때까지 기다리고(await는 '기다리다’라는 뜻) 결과는 그 이후 반환

```js
async function f() {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000);
  });

  let result = await promise; // 프라미스가 이행될 때까지 기다림 (*)

  alert(result); // 1초 후에 "완료!"
}

f();
```

함수를 호출하고, 함수 본문이 실행되는 도중에 (\*)로 표시한 줄에서 실행이 잠시 '중단’되었다가 프라미스가 처리되면 실행이 재개

프라미스가 처리되면 그 결과와 함께 실행이 재개  
프라미스가 처리되길 기다리는 동안엔 엔진이 다른 일(다른 스크립트를 실행, 이벤트 처리 등)을 할 수 있기 때문에, CPU 리소스가 낭비되지 않음

일반 함수엔 await를 사용할 수 없음

```js
function f() {
  let promise = Promise.resolve(1);
  let result = await promise; // Syntax error
}
```

프라미스 체이닝 예시를 async/await를 사용해 다시 작성해보기

1. 먼저 `.then` 호출을 await로 바꾸기
2. function 앞에 async를 붙여 await를 사용할 수 있도록 하기

```js
async function showAvatar() {
  // JSON 읽기
  let response = await fetch("/article/promise-chaining/user.json");
  let user = await response.json();

  // github 사용자 정보 읽기
  let githubResponse = await fetch(`https://api.github.com/users/${user.name}`);
  let githubUser = await githubResponse.json();

  // 아바타 보여주기
  let img = document.createElement("img");
  img.src = githubUser.avatar_url;
  img.className = "promise-avatar-example";
  document.body.append(img);

  // 3초 대기
  await new Promise((resolve, reject) => setTimeout(resolve, 3000));

  img.remove();

  return githubUser;
}

showAvatar();
```

await는 최상위 레벨 코드에서 작동하지 않음

```js
// 최상위 레벨 코드에선 문법 에러가 발생함
let response = await fetch("/article/promise-chaining/user.json");
let user = await response.json();
```

익명 함수로 감싸면 가능

```js
(async () => {
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();
  ...
})();
```

`promise.then`처럼 await에도 thenable 객체(then 메서드가 있는 호출 가능한 객체)를 사용할 수 있음

```js
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve);
    // 1000밀리초 후에 이행됨(result는 this.num*2)
    setTimeout(() => resolve(this.num * 2), 1000); // (*)
  }
}

async function f() {
  // 1초 후, 변수 result는 2가 됨
  let result = await new Thenable(1);
  alert(result);
}

f();
```

await는 `.then`이 구현되어있으면서 프라미스가 아닌 객체를 받으면, 내장 함수 resolve와 reject를 인수로 제공하는 메서드인 `.then`을 호출(일반 Promise executor가 하는 일과 동일)  
그리고 나서 await는 resolve와 reject 중 하나가 호출되길 기다렸다가((\*)로 표시한 줄) 호출 결과를 가지고 다음 일을 진행

## 에러 핸들링

프라미스가 거부되면 마치 throw문을 작성한 것처럼 에러가 던져짐

```js
async function f() {
  await Promise.reject(new Error("에러 발생!"));
}

// 같은 동작
async function f() {
  throw new Error("에러 발생!");
}
```

await가 던진 에러는 throw가 던진 에러를 잡을 때처럼 try..catch를 사용해 잡을 수 있음

```js
async function f() {
  try {
    let response = await fetch("http://유효하지-않은-주소");
    let user = await response.json();
  } catch (err) {
    // fetch와 response.json에서 발행한 에러 모두를 여기서 잡습니다.
    alert(err);
  }
}

f();
```

try..catch가 없으면 아래 예시의 async 함수 `f()`를 호출해 만든 프라미스가 거부 상태가 됨  
`f()`에 `.catch`를 추가하면 거부된 프라미스를 처리할 수 있음

```js
async function f() {
  let response = await fetch("http://유효하지-않은-주소");
}

// f()는 거부 상태의 프라미스가 됩니다.
f().catch(alert); // TypeError: failed to fetch
```

여러 개의 프라미스가 모두 처리되길 기다려야 하는 상황이라면 이 프라미스들을 Promise.all로 감싸고 여기에 await를 붙여 사용 가능

# 13. 모듈

## 모듈이란

모듈은 단지 파일 하나에 불과, 스크립트 하나는 모듈 하나

파일을 여러 개로 분리할 때, 분리된 파일 각각을 '모듈(module)'이라고 부르는데, 모듈은 대개 클래스 하나 혹은 특정한 목적을 가진 복수의 함수로 구성된 라이브러리 하나로 구성됨

모듈에 특수한 지시자 export와 import를 적용하면 다른 모듈을 불러와 불러온 모듈에 있는 함수를 호출하는 것과 같은 기능 공유가 가능

- export 지시자를 변수나 함수 앞에 붙이면 외부 모듈에서 해당 변수나 함수에 접근할 수 있음(모듈 내보내기)
  ` import 지시자를 사용하면 외부 모듈의 기능을 가져올 수 있음(모듈 가져오기)

내보내기

```js
// 📁 sayHi.js
export function sayHi(user) {
  alert(`Hello, ${user}!`);
}
```

사용하기

```js
// 📁 main.js
import { sayHi } from "./sayHi.js";

alert(sayHi); // 함수
sayHi("John"); // Hello, John!
```

모듈은 특수한 키워드나 기능과 함께 사용되므로 `<script type="module">` 같은 속성을 설정해 해당 스크립트가 모듈이란 걸 브라우저가 알 수 있게 해줘야 함

```html
<!DOCTYPE html>
<script type="module">
  import { sayHi } from "./say.js";

  document.body.innerHTML = sayHi("John");
</script>
```

```js
export function sayHi(user) {
  return `Hello, ${user}!`;
}
```

## 모듈의 핵심 기능

### 엄격 모드로 실행됨

모듈은 항상 엄격 모드(use strict)로 실행

### 모듈 레벨 스코프

모듈 내부에서 정의한 변수나 함수는 다른 스크립트에서 접근할 수 없음

### 단 한 번만 평가됨

동일한 모듈이 여러 곳에서 사용되더라도 모듈은 최초 호출 시 단 한 번만 실행

실행된 모듈은 필요한 곳에 공유되므로 어느 한 모듈에서 admin 객체를 수정하면 다른 모듈에서도 변경사항을 확인할 수 있음

```js
// 📁 admin.js
export let admin = {};

export function sayHi() {
  alert(`${admin.name}님, 안녕하세요!`);
}
```

```js
// 📁 init.js
import { admin } from "./admin.js";
admin.name = "보라";
```

```js
// 📁 other.js
import { admin, sayHi } from "./admin.js";

alert(admin.name); // 보라

sayHi(); // 보라님, 안녕하세요!
```

### import.meta

import.meta 객체는 현재 모듈에 대한 정보를 제공

호스트 환경에 따라 제공하는 정보의 내용은 다른데, 브라우저 환경에선 스크립트의 URL 정보를 얻을 수 있음  
HTML 안에 있는 모듈이라면, 현재 실행 중인 웹페이지의 URL 정보를 얻을 수 있음

```js
<script type="module">
  alert(import.meta.url); // script URL (인라인 스크립트가 위치해 있는 html
  페이지의 URL)
</script>
```

### this는 undefined

모듈 최상위 레벨의 this는 undefined

모듈이 아닌 일반 스크립트의 this는 전역 객체인 것과 대조

```js
<script>
  alert(this); // window
</script>

<script type="module">
  alert(this); // undefined
</script>
```

## 브라우저 특정 기능

브라우저 환경에서 `type="module"`이 붙은 스크립트가 일반 스크립트와 다른 점

### 지연 실행

모듈 스크립트는 항상 지연 실행  
외부 스크립트, 인라인 스크립트와 관계없이 마치 defer 속성을 붙인 것처럼 실행

- 외부 모듈 스크립트 `<script type="module" src="...">`를 다운로드할 때 브라우저의 HTML 처리가 멈추지 않음
  - 브라우저는 외부 모듈 스크립트와 기타 리소스를 병렬적으로 불러옴
- 모듈 스크립트는 HTML 문서가 완전히 준비될 때까지 대기 상태에 있다가 HTML 문서가 완전히 만들어진 이후에 실행
  - 모듈의 크기가 아주 작아서 HTML보다 빨리 불러온 경우도 마찬가지
- 스크립트의 상대적 순서가 유지. 문서상 위쪽의 스크립트부터 차례로 실행

이런 특징 때문에 모듈 스크립트는 항상 완전한 HTML 페이지를 ‘볼 수’ 있고 문서 내 요소에도 접근할 수 있음

```html
<script type="module">
  alert(typeof button); // 모듈 스크립트는 지연 실행되기 때문에 페이지가 모두 로드되고 난 다음에 alert 함수가 실행되므로
  // 얼럿창에 object가 정상적으로 출력됩니다. 모듈 스크립트는 아래쪽의 button 요소를 '볼 수' 있죠.
</script>

하단의 일반 스크립트와 비교해 봅시다.

<script>
  alert(typeof button); // 일반 스크립트는 페이지가 완전히 구성되기 전이라도 바로 실행됩니다.
  // 버튼 요소가 페이지에 만들어지기 전에 접근하였기 때문에 undefined가 출력되는 것을 확인할 수 있습니다.
</script>

<button id="button">Button</button>
<!-- undefined가 먼저, object는 나중에 출력 -->
```

### 인라인 스크립트의 비동기 처리

모듈이 아닌 일반 스크립트에서 async 속성은 외부 스크립트를 불러올 때만 유효  
async 속성이 붙은 스크립트는 로딩이 끝나면 다른 스크립트나 HTML 문서가 처리되길 기다리지 않고 바로 실행

모듈 스크립트에선 async 속성을 인라인 스크립트에도 적용  
아래 인라인 스크립트엔 async 속성이 붙었기 때문에 다른 스크립트나 HTML이 처리되길 기다리지 않고 바로 실행

```html
<!-- 필요한 모듈(analytics.js)의 로드가 끝나면 -->
<!-- 문서나 다른 <script>가 로드되길 기다리지 않고 바로 실행됩니다.-->
<script async type="module">
  import { counter } from "./analytics.js";

  counter.count();
</script>
```

### 외부 스크립트

1. src 속성값이 동일한 외부 스크립트는 한 번만 실행

```html
<!-- my.js는 한 번만 로드 및 실행됩니다. -->
<script type="module" src="my.js"></script>
<script type="module" src="my.js"></script>
```

2. 외부 사이트같이 다른 오리진에서 모듈 스크립트를 불러오려면 CORS 챕터에서 설명한 바와 같이 CORS 헤더가 필요
   - 모듈이 저장되어있는 원격 서버가 `Access-Control-Allow-Origin: *` 헤더를 제공해야만 외부 모듈을 불러올 수 있음 참고로 `*` 대신 페치(fetch)를 허용할 도메인을 명시할 수도 있음

```html
<!-- another-site.com이 Access-Control-Allow-Origin을 지원해야만 외부 모듈을 불러올 수 있습니다.-->
<!-- 그렇지 않으면 스크립트는 실행되지 않습니다.-->
<script type="module" src="http://another-site.com/their.js"></script>
```

### 경로가 없는 모듈은 금지

브라우저 환경에서 import는 반드시 상대 혹은 절대 URL 앞에 와야 함

```js
import { sayHi } from "sayHi"; // Error!
// './sayHi.js'와 같이 경로 정보를 지정해 주어야 합니다.
```

### 호환을 위한 nomodule

구식 브라우저는 type="module"을 해석하지 못하기 때문에 nomodule 속성을 사용

```html
<script type="module">
  alert("모던 브라우저를 사용하고 계시군요.");
</script>

<script nomodule>
  alert(
    "type=module을 해석할 수 있는 브라우저는 nomodule 타입의 스크립트는 넘어갑니다. 따라서 이 alert 문은 실행되지 않습니다."
  );
  alert(
    "오래된 브라우저를 사용하고 있다면 type=module이 붙은 스크립트는 무시됩니다. 대신 이 alert 문이 실행됩니다."
  );
</script>
```

## 모듈 내보내고 가져오기

## 선언부 앞에 export 붙이기

```js
// 배열 내보내기
export let months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

// 상수 내보내기
export const MODULES_BECAME_STANDARD_YEAR = 2015;

// 클래스 내보내기
export class User {
  constructor(name) {
    this.name = name;
  }
}
```

대부분의 자바스크립트 스타일 가이드는 함수나 클래스 선언 끝에 세미콜론을 붙이지 말라고 권유

## 선언부와 떨어진 곳에 export 붙이기

```js
// 📁 say.js
function sayHi(user) {
  alert(`Hello, ${user}!`);
}

function sayBye(user) {
  alert(`Bye, ${user}!`);
}

export { sayHi, sayBye }; // 두 함수를 내보냄
```

## import \*

```js
// 📁 main.js
import { sayHi, sayBye } from "./say.js";

sayHi("John"); // Hello, John!
sayBye("John"); // Bye, John!
```

한꺼번에 가져오기

```js
// 📁 main.js
import * as say from "./say.js";

say.sayHi("John");
say.sayBye("John");
```

## import ‘as’

as를 사용하면 이름을 바꿔서 모듈을 가져올 수 있음

```js
// 📁 main.js
import { sayHi as hi, sayBye as bye } from "./say.js";

hi("John"); // Hello, John!
bye("John"); // Bye, John!
```

## Export ‘as’

이름 바꿔 내보내기

```js
// 📁 say.js
...
export {sayHi as hi, sayBye as bye};
```

```js
// 📁 main.js
import * as say from "./say.js";

say.hi("John"); // Hello, John!
say.bye("John"); // Bye, John!
```

## export default

export default를 사용하면 '해당 모듈엔 개체가 하나만 있다’는 사실을 명확히 나타낼 수 있음

```js
// 📁 user.js
export default class User {
  // export 옆에 'default'를 추가해보았습니다.
  constructor(name) {
    this.name = name;
  }
}
```

default를 붙여서 모듈을 내보내면 중괄호 {} 없이 모듈을 가져올 수 있음

```js
// 📁 main.js
import User from "./user.js"; // {User}가 아닌 User로 클래스를 가져왔습니다.

new User("John");
```

![image](https://github.com/user-attachments/assets/9776748e-afc6-43cb-9b64-35131d9d51d0)  
한 파일엔 named export나 default export 둘 중 하나만 사용

export default는 파일당 하나만 있으므로 이 개체를 가져오기 하려는 모듈에선 중괄호 없이도 어떤 개체를 가지고 올지 정확히 알 수 있으므로 이름이 없어도 괜찮음

```js
export default class { // 클래스 이름이 없음
  constructor() { ... }
}
```

```js
export default function (user) {
  // 함수 이름이 없음
  alert(`Hello, ${user}!`);
}
```

### ‘default’ name

```js
// 📁 user.js
// default 한 개
export default class User {
  constructor(name) {
    this.name = name;
  }
}

// named export 여러 개
export function sayHi(user) {
  alert(`Hello, ${user}!`);
}
```

default export와 named export를 동시에 가져오기

```js
// 📁 main.js
import { default as User, sayHi } from "./user.js";

new User("John");
```

## 모듈 다시 내보내기

`export ... from ...` 문법을 사용하면 가져온 개체를 즉시 ‘다시 내보내기(re-export)’ 할 수 있음

```js
export { sayHi } from "./say.js"; // sayHi를 다시 내보내기 함

export { default as User } from "./user.js"; // default export를 다시 내보내기 함
```

부 개발자가 패키지 안의 파일들을 뒤져 내부 구조를 건드리게 하면 안 됨. 그러려면 공개할 것만 auth/index.js에 넣어 내보내기 하고 나머지는 숨기는 게 좋음

이때 내보낼 기능을 패키지 전반에 분산하여 구현한 후, auth/index.js에서 이 기능들을 가져오고 이를 다시 내보내면 원하는 바를 어느 정도 달성할 수 있음

**import/export 문은 블록 {...}안에선 동작하지 않는다는 점에 유의**

## 동적으로 모듈 가져오기

## import() 표현식

import(module) 표현식은 모듈을 읽고 이 모듈이 내보내는 것들을 모두 포함하는 객체를 담은 이행된 프라미스를 반환. 호출은 어디서나 가능

```js
let modulePath = prompt("어떤 모듈을 불러오고 싶으세요?");

import(modulePath)
  .then(obj => <모듈 객체>)
  .catch(err => <로딩 에러, e.g. 해당하는 모듈이 없는 경우>)
```

async 함수 안에서 `let module = await import(modulePath)`와 같이 사용하는 것도 가능

```js
// 📁 say.js
export function hi() {
  alert(`안녕하세요.`);
}

export function bye() {
  alert(`안녕히 가세요.`);
}
```

```js
let { hi, bye } = await import("./say.js");

hi();
bye();
```

import()는 함수 호출과 문법이 유사해 보이긴 하지만 함수 호출은 아님  
따라서 import를 변수에 복사한다거나 call/apply를 사용하는 것이 불가능

# 14. 기타

## Proxy

Proxy : 특정 객체를 감싸 프로퍼티 읽기, 쓰기와 같은 객체에 가해지는 작업을 중간에서 가로채는 객체  
가로채진 작업은 Proxy 자체에서 처리되기도 하고, 원래 객체가 처리하도록 그대로 전달되기도 함

```js
let proxy = new Proxy(target, handler);
```

- target : 감싸게 될 객체로, 함수를 포함한 모든 객체가 가능
- handler : 동작을 가로채는 메서드인 '트랩(trap)'이 담긴 객체로, 여기서 프락시를 설정(예시: get 트랩은 target의 프로퍼티를 읽을 때, set 트랩은 target의 프로퍼티를 쓸 때 활성화됨)

proxy에 작업이 가해지고, handler에 작업과 상응하는 트랩이 있으면 트랩이 실행되어 프락시가 이 작업을 처리할 기회를 얻게 됨  
트랩이 없으면 target에 작업이 직접 수행

트랩이 없는 프락시

```js
let target = {};
let proxy = new Proxy(target, {}); // 빈 핸들러

proxy.test = 5; // 프락시에 값을 씁니다. -- (1)
alert(target.test); // 5, target에 새로운 프로퍼티가 생겼네요!

alert(proxy.test); // 5, 프락시를 사용해 값을 읽을 수도 있습니다. -- (2)

for (let key in proxy) alert(key); // test, 반복도 잘 동작합니다. -- (3)
```

위 예시의 프락시엔 트랩이 없기 때문에 proxy에 가해지는 모든 작업은 target에 전달

![image](https://github.com/user-attachments/assets/d794b62b-6284-4cfa-8dbf-f259f7b6019c)

proxy는 target을 둘러싸는 투명한 래퍼가 됨

Proxy는 일반 객체와는 다른 행동 양상을 보이는 '특수 객체(exotic object)'  
프로퍼티가 없어서 handler가 비어있으면 Proxy에 가해지는 작업은 target에 곧바로 전달됨

프락시의 트랩은 내부 메서드의 호출을 가로챔

프락시가 가로채는 내부 메서드 리스트

![image](https://github.com/user-attachments/assets/b0d3a5b8-d800-4b8b-8767-dbfb86fb813d)

## get 트랩으로 프로퍼티 기본값 설정하기

가장 흔히 볼 수 있는 트랩은 프로퍼티를 읽거나 쓸 때 사용되는 트랩

프로퍼티 읽기를 가로채려면 handler에 get(target, property, receiver) 메서드가 있어야 함

get메서드는 프로퍼티를 읽으려고 할 때 작동

- target : 동작을 전달할 객체로 new Proxy의 첫 번째 인자
- property : 프로퍼티 이름
- receiver : 타깃 프로퍼티가 getter라면 receiver는 getter가 호출될 때 this임. 대개는 proxy 객체 자신이 this가 됨.프락시 객체를 상속받은 객체가 있다면 해당 객체가 this가 되기도 함

```js
let dictionary = {
  Hello: "안녕하세요",
  Bye: "안녕히 가세요",
};

dictionary = new Proxy(dictionary, {
  get(target, phrase) {
    // 프로퍼티를 읽기를 가로챕니다.
    if (phrase in target) {
      // 조건: 사전에 구절이 있는 경우
      return target[phrase]; // 번역문을 반환합니다
    } else {
      // 구절이 없는 경우엔 구절 그대로를 반환합니다.
      return phrase;
    }
  },
});

// 사전을 검색해봅시다!
// 사전에 없는 구절을 입력하면 입력값이 그대로 반환됩니다.
alert(dictionary["Hello"]); // 안녕하세요
alert(dictionary["Welcome to Proxy"]); // Welcome to Proxy (입력값이 그대로 출력됨)
```

## set 트랩으로 프로퍼티 값 검증하기

set 트랩은 프로퍼티에 값을 쓰려고 할 때 이를 가로챔

- target : 동작을 전달할 객체로 new Proxy의 첫 번째 인자
- property : 프로퍼티 이름
- value : 프로퍼티 값
- receiver : get 트랩과 유사하게 동작하는 객체로, setter 프로퍼티에만 관여

set 트랩을 사용해 배열에 추가하려는 값이 숫자형인지 검증

```js
let numbers = [];

numbers = new Proxy(numbers, {
  // (*)
  set(target, prop, val) {
    // 프로퍼티에 값을 쓰는 동작을 가로챕니다.
    if (typeof val == "number") {
      target[prop] = val;
      return true;
    } else {
      return false;
    }
  },
});

numbers.push(1); // 추가가 성공했습니다.
numbers.push(2); // 추가가 성공했습니다.
alert("Length is: " + numbers.length); // 2

numbers.push("test"); // Error: 'set' on proxy

alert("윗줄에서 에러가 발생했기 때문에 이 줄은 절대 실행되지 않습니다.");
```

숫자형 값을 설정하려 할 때만 true를, 그렇지 않은 경우엔(TypeError가 트리거되고) false를 반환하도록 함

set 트랩을 사용할 땐 값을 쓰는 게 성공했을 때 반드시 true를 반환  
true를 반환하지 않았거나 falsy한 값을 반환하게 되면 TypeError가 발생

## ownKeys와 getOwnPropertyDescriptor로 반복 작업하기

Object.keys, for..in 반복문을 비롯한 프로퍼티 순환 관련 메서드 대다수는 내부 메서드 [[OwnPropertyKeys]](트랩 메서드는 ownKeys임)를 사용해 프로퍼티 목록을 얻음

- Object.getOwnPropertyNames(obj) : 심볼형이 아닌 키만 반환
- Object.getOwnPropertySymbols(obj) : 심볼형 키만 반환
- Object.keys/values() : enumerable 플래그가 true이면서 심볼형이 아닌 키나 심볼형이 아닌 키에 해당하는 값 전체를 반환
- for..in 반복문 : enumerable 플래그가 true인 심볼형이 아닌 키, 프로토타입 키를 순회

## Reflect

Reflect : Proxy의 생성을 간소화하는 내장 객체

ReflectProxy에 의해 트랩 가능한 모든 내부 메서드에는 트랩과 동일한 이름과 인수를 갖는 Proxy해당 메서드가 있음

## Eval: 문자열 코드 실행하기

내장 함수 eval을 사용하면 문자열 형태의 코드를 실행할 수 있음

```js
let result = eval(code);
```

```js
let code = 'alert("Hello")';
eval(code); // Hello
```

잘 사용하지 않음

## 커링

커링 : `f(a, b, c)`처럼 단일 호출로 처리하는 함수를 `f(a)(b)(c)`와 같이 각각의 인수가 호출 가능한 프로세스로 호출된 후 병합되도록 변환하는 것

```js
function curry(f) {
  // 커링 변환을 하는 curry(f) 함수
  return function (a) {
    return function (b) {
      return f(a, b);
    };
  };
}

// usage
function sum(a, b) {
  return a + b;
}

let curriedSum = curry(sum);

alert(curriedSum(1)(2)); // 3
```

- curry(func)의 반환값은 function(a)형태의 래퍼
- curriedSum(1)같은 함수가 호출되었을 때, 그 인수는 렉시컬 환경에 저장이 되고 새로운 래퍼 function(b)이 반환
- 반환된 function(b)래퍼 함수가 2를 인수로 호출됨. 그리고 반환값이 원래의 sum으로 넘겨져서 호출

# 🧐 질문
